#!/system/bin/sh
dnaPath=/data/data/org.servalproject

#set my number
echo -n $1 > $dnaPath/tmp/myNumber.tmp

#create the record of the new subscriber
busybox time -p $dnaPath/bin/dna -d $1 -C > $dnaPath/tmp/newSid.tmp
sid=`busybox grep "^OK:" $dnaPath/tmp/newSid.tmp | busybox cut -f2 -d:`
echo SID:$sid

#get the location
#( ifconfig eth0 ; ifconfig tiwlan0 ) 2>&1 | busybox grep ip > $dnaPath/tmp/testLocation.tmp
#temp2=`echo ${temp#t*ip }`
#ipAdress=`echo ${temp2% mask*]}`
ipAdress=`( ifconfig eth0 ; ifconfig tiwlan0 ) 2>&1 | busybox grep ip | busybox cut -f3 -d" "`
#ipAdress=${temp%% *}       
location=4000@$ipAdress                                       
echo $location                                                
echo $location > $dnaPath/tmp/location.tmp

#set the location in the dna
$dnaPath/bin/dna -s $sid -i 0 -W locations=$location
