#!/system/bin/sh

dnaPath=/data/data/org.servalproject

if busybox test -s "$dnaPath/tmp/isFirst.tmp"
then
	# phone already use one 
	echo "0" > $dnaPath/tmp/isFirst.tmp
else
	# phone never use
	echo "1" > $dnaPath/tmp/isFirst.tmp
fi
