#!/system/bin/sh

dnaPath=/data/data/org.servalproject

if busybox test -s "$dnaPath/tmp/location.tmp"
then
	# voice sig is found by the dna
	echo "1" > $dnaPath/tmp/locationFound.tmp
else
	# number is not found
	echo "0" > $dnaPath/tmp/locationFound.tmp
fi
