#!/system/bin/sh

dnaPath=/data/data/org.servalproject

if busybox test -s "$dnaPath/tmp/myNumber.tmp"
then
	# phone already use one 
	echo "1" > $dnaPath/tmp/isNumberSet.tmp
else
	# phone never use
	echo "0" > $dnaPath/tmp/isNumberSet.tmp
fi
