#!/system/bin/sh

dnaPath=/data/data/org.servalproject

if busybox test -s "$dnaPath/tmp/voicesig.gsm"
then
	# voice sig is found by the dna
	echo "1" > $dnaPath/tmp/voiceSigFound.tmp
else
	# number is not found
	echo "0" > $dnaPath/tmp/voiceSigFound.tmp
fi
