// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MeshMS.proto

package org.servalproject.meshms;

public final class MeshMSProtobuf {
  private MeshMSProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MeshMSOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string sender = 1;
    boolean hasSender();
    String getSender();
    
    // optional string recipient = 2;
    boolean hasRecipient();
    String getRecipient();
    
    // optional string type = 3;
    boolean hasType();
    String getType();
    
    // optional int32 typeInt = 4;
    boolean hasTypeInt();
    int getTypeInt();
    
    // optional int64 timestamp = 5;
    boolean hasTimestamp();
    long getTimestamp();
    
    // repeated .MeshMS.ContentElem content = 6;
    java.util.List<org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem> 
        getContentList();
    org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem getContent(int index);
    int getContentCount();
    java.util.List<? extends org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElemOrBuilder> 
        getContentOrBuilderList();
    org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElemOrBuilder getContentOrBuilder(
        int index);
  }
  public static final class MeshMS extends
      com.google.protobuf.GeneratedMessage
      implements MeshMSOrBuilder {
    // Use MeshMS.newBuilder() to construct.
    private MeshMS(Builder builder) {
      super(builder);
    }
    private MeshMS(boolean noInit) {}
    
    private static final MeshMS defaultInstance;
    public static MeshMS getDefaultInstance() {
      return defaultInstance;
    }
    
    public MeshMS getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.servalproject.meshms.MeshMSProtobuf.internal_static_MeshMS_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.servalproject.meshms.MeshMSProtobuf.internal_static_MeshMS_fieldAccessorTable;
    }
    
    public interface ContentElemOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional string type = 1;
      boolean hasType();
      String getType();
      
      // optional int32 typeInt = 2;
      boolean hasTypeInt();
      int getTypeInt();
      
      // optional string content = 3;
      boolean hasContent();
      String getContent();
    }
    public static final class ContentElem extends
        com.google.protobuf.GeneratedMessage
        implements ContentElemOrBuilder {
      // Use ContentElem.newBuilder() to construct.
      private ContentElem(Builder builder) {
        super(builder);
      }
      private ContentElem(boolean noInit) {}
      
      private static final ContentElem defaultInstance;
      public static ContentElem getDefaultInstance() {
        return defaultInstance;
      }
      
      public ContentElem getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.servalproject.meshms.MeshMSProtobuf.internal_static_MeshMS_ContentElem_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.servalproject.meshms.MeshMSProtobuf.internal_static_MeshMS_ContentElem_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional string type = 1;
      public static final int TYPE_FIELD_NUMBER = 1;
      private java.lang.Object type_;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            type_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional int32 typeInt = 2;
      public static final int TYPEINT_FIELD_NUMBER = 2;
      private int typeInt_;
      public boolean hasTypeInt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTypeInt() {
        return typeInt_;
      }
      
      // optional string content = 3;
      public static final int CONTENT_FIELD_NUMBER = 3;
      private java.lang.Object content_;
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getContent() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            content_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        type_ = "";
        typeInt_ = 0;
        content_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, typeInt_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getContentBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, typeInt_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getContentBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.servalproject.meshms.MeshMSProtobuf.internal_static_MeshMS_ContentElem_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.servalproject.meshms.MeshMSProtobuf.internal_static_MeshMS_ContentElem_fieldAccessorTable;
        }
        
        // Construct using org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          type_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          typeInt_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          content_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.getDescriptor();
        }
        
        public org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem getDefaultInstanceForType() {
          return org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.getDefaultInstance();
        }
        
        public org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem build() {
          org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem buildPartial() {
          org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem result = new org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.typeInt_ = typeInt_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.content_ = content_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem) {
            return mergeFrom((org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem other) {
          if (other == org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.getDefaultInstance()) return this;
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasTypeInt()) {
            setTypeInt(other.getTypeInt());
          }
          if (other.hasContent()) {
            setContent(other.getContent());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                type_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                typeInt_ = input.readInt32();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                content_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional string type = 1;
        private java.lang.Object type_ = "";
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            type_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setType(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = getDefaultInstance().getType();
          onChanged();
          return this;
        }
        void setType(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
        }
        
        // optional int32 typeInt = 2;
        private int typeInt_ ;
        public boolean hasTypeInt() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getTypeInt() {
          return typeInt_;
        }
        public Builder setTypeInt(int value) {
          bitField0_ |= 0x00000002;
          typeInt_ = value;
          onChanged();
          return this;
        }
        public Builder clearTypeInt() {
          bitField0_ = (bitField0_ & ~0x00000002);
          typeInt_ = 0;
          onChanged();
          return this;
        }
        
        // optional string content = 3;
        private java.lang.Object content_ = "";
        public boolean hasContent() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public String getContent() {
          java.lang.Object ref = content_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            content_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setContent(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          content_ = value;
          onChanged();
          return this;
        }
        public Builder clearContent() {
          bitField0_ = (bitField0_ & ~0x00000004);
          content_ = getDefaultInstance().getContent();
          onChanged();
          return this;
        }
        void setContent(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000004;
          content_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:MeshMS.ContentElem)
      }
      
      static {
        defaultInstance = new ContentElem(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:MeshMS.ContentElem)
    }
    
    private int bitField0_;
    // optional string sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private java.lang.Object sender_;
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sender_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string recipient = 2;
    public static final int RECIPIENT_FIELD_NUMBER = 2;
    private java.lang.Object recipient_;
    public boolean hasRecipient() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getRecipient() {
      java.lang.Object ref = recipient_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          recipient_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRecipientBytes() {
      java.lang.Object ref = recipient_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        recipient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 typeInt = 4;
    public static final int TYPEINT_FIELD_NUMBER = 4;
    private int typeInt_;
    public boolean hasTypeInt() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getTypeInt() {
      return typeInt_;
    }
    
    // optional int64 timestamp = 5;
    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // repeated .MeshMS.ContentElem content = 6;
    public static final int CONTENT_FIELD_NUMBER = 6;
    private java.util.List<org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem> content_;
    public java.util.List<org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem> getContentList() {
      return content_;
    }
    public java.util.List<? extends org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElemOrBuilder> 
        getContentOrBuilderList() {
      return content_;
    }
    public int getContentCount() {
      return content_.size();
    }
    public org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem getContent(int index) {
      return content_.get(index);
    }
    public org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElemOrBuilder getContentOrBuilder(
        int index) {
      return content_.get(index);
    }
    
    private void initFields() {
      sender_ = "";
      recipient_ = "";
      type_ = "";
      typeInt_ = 0;
      timestamp_ = 0L;
      content_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSenderBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRecipientBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, typeInt_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, timestamp_);
      }
      for (int i = 0; i < content_.size(); i++) {
        output.writeMessage(6, content_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSenderBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRecipientBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, typeInt_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timestamp_);
      }
      for (int i = 0; i < content_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, content_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.servalproject.meshms.MeshMSProtobuf.MeshMS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.servalproject.meshms.MeshMSProtobuf.MeshMS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.servalproject.meshms.MeshMSProtobuf.MeshMS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.servalproject.meshms.MeshMSProtobuf.MeshMS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.servalproject.meshms.MeshMSProtobuf.MeshMS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.servalproject.meshms.MeshMSProtobuf.MeshMS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.servalproject.meshms.MeshMSProtobuf.MeshMS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.servalproject.meshms.MeshMSProtobuf.MeshMS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.servalproject.meshms.MeshMSProtobuf.MeshMS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.servalproject.meshms.MeshMSProtobuf.MeshMS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.servalproject.meshms.MeshMSProtobuf.MeshMS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.servalproject.meshms.MeshMSProtobuf.MeshMSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.servalproject.meshms.MeshMSProtobuf.internal_static_MeshMS_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.servalproject.meshms.MeshMSProtobuf.internal_static_MeshMS_fieldAccessorTable;
      }
      
      // Construct using org.servalproject.meshms.MeshMSProtobuf.MeshMS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sender_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        recipient_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        typeInt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (contentBuilder_ == null) {
          content_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          contentBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.servalproject.meshms.MeshMSProtobuf.MeshMS.getDescriptor();
      }
      
      public org.servalproject.meshms.MeshMSProtobuf.MeshMS getDefaultInstanceForType() {
        return org.servalproject.meshms.MeshMSProtobuf.MeshMS.getDefaultInstance();
      }
      
      public org.servalproject.meshms.MeshMSProtobuf.MeshMS build() {
        org.servalproject.meshms.MeshMSProtobuf.MeshMS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.servalproject.meshms.MeshMSProtobuf.MeshMS buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.servalproject.meshms.MeshMSProtobuf.MeshMS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.servalproject.meshms.MeshMSProtobuf.MeshMS buildPartial() {
        org.servalproject.meshms.MeshMSProtobuf.MeshMS result = new org.servalproject.meshms.MeshMSProtobuf.MeshMS(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.recipient_ = recipient_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.typeInt_ = typeInt_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timestamp_ = timestamp_;
        if (contentBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            content_ = java.util.Collections.unmodifiableList(content_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.servalproject.meshms.MeshMSProtobuf.MeshMS) {
          return mergeFrom((org.servalproject.meshms.MeshMSProtobuf.MeshMS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.servalproject.meshms.MeshMSProtobuf.MeshMS other) {
        if (other == org.servalproject.meshms.MeshMSProtobuf.MeshMS.getDefaultInstance()) return this;
        if (other.hasSender()) {
          setSender(other.getSender());
        }
        if (other.hasRecipient()) {
          setRecipient(other.getRecipient());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTypeInt()) {
          setTypeInt(other.getTypeInt());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (contentBuilder_ == null) {
          if (!other.content_.isEmpty()) {
            if (content_.isEmpty()) {
              content_ = other.content_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureContentIsMutable();
              content_.addAll(other.content_);
            }
            onChanged();
          }
        } else {
          if (!other.content_.isEmpty()) {
            if (contentBuilder_.isEmpty()) {
              contentBuilder_.dispose();
              contentBuilder_ = null;
              content_ = other.content_;
              bitField0_ = (bitField0_ & ~0x00000020);
              contentBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getContentFieldBuilder() : null;
            } else {
              contentBuilder_.addAllMessages(other.content_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sender_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              recipient_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              type_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              typeInt_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timestamp_ = input.readInt64();
              break;
            }
            case 50: {
              org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.Builder subBuilder = org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addContent(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string sender = 1;
      private java.lang.Object sender_ = "";
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSender(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
        return this;
      }
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      void setSender(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
      }
      
      // optional string recipient = 2;
      private java.lang.Object recipient_ = "";
      public boolean hasRecipient() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getRecipient() {
        java.lang.Object ref = recipient_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          recipient_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRecipient(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        recipient_ = value;
        onChanged();
        return this;
      }
      public Builder clearRecipient() {
        bitField0_ = (bitField0_ & ~0x00000002);
        recipient_ = getDefaultInstance().getRecipient();
        onChanged();
        return this;
      }
      void setRecipient(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        recipient_ = value;
        onChanged();
      }
      
      // optional string type = 3;
      private java.lang.Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
      }
      
      // optional int32 typeInt = 4;
      private int typeInt_ ;
      public boolean hasTypeInt() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getTypeInt() {
        return typeInt_;
      }
      public Builder setTypeInt(int value) {
        bitField0_ |= 0x00000008;
        typeInt_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypeInt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        typeInt_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 timestamp = 5;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000010;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .MeshMS.ContentElem content = 6;
      private java.util.List<org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem> content_ =
        java.util.Collections.emptyList();
      private void ensureContentIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          content_ = new java.util.ArrayList<org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem>(content_);
          bitField0_ |= 0x00000020;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem, org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.Builder, org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElemOrBuilder> contentBuilder_;
      
      public java.util.List<org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem> getContentList() {
        if (contentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(content_);
        } else {
          return contentBuilder_.getMessageList();
        }
      }
      public int getContentCount() {
        if (contentBuilder_ == null) {
          return content_.size();
        } else {
          return contentBuilder_.getCount();
        }
      }
      public org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem getContent(int index) {
        if (contentBuilder_ == null) {
          return content_.get(index);
        } else {
          return contentBuilder_.getMessage(index);
        }
      }
      public Builder setContent(
          int index, org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.set(index, value);
          onChanged();
        } else {
          contentBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setContent(
          int index, org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.set(index, builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addContent(org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.add(value);
          onChanged();
        } else {
          contentBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addContent(
          int index, org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.add(index, value);
          onChanged();
        } else {
          contentBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addContent(
          org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.add(builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addContent(
          int index, org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.add(index, builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllContent(
          java.lang.Iterable<? extends org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem> values) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          super.addAll(values, content_);
          onChanged();
        } else {
          contentBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          contentBuilder_.clear();
        }
        return this;
      }
      public Builder removeContent(int index) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.remove(index);
          onChanged();
        } else {
          contentBuilder_.remove(index);
        }
        return this;
      }
      public org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.Builder getContentBuilder(
          int index) {
        return getContentFieldBuilder().getBuilder(index);
      }
      public org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElemOrBuilder getContentOrBuilder(
          int index) {
        if (contentBuilder_ == null) {
          return content_.get(index);  } else {
          return contentBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElemOrBuilder> 
           getContentOrBuilderList() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(content_);
        }
      }
      public org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.Builder addContentBuilder() {
        return getContentFieldBuilder().addBuilder(
            org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.getDefaultInstance());
      }
      public org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.Builder addContentBuilder(
          int index) {
        return getContentFieldBuilder().addBuilder(
            index, org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.getDefaultInstance());
      }
      public java.util.List<org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.Builder> 
           getContentBuilderList() {
        return getContentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem, org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.Builder, org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElemOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem, org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.Builder, org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElemOrBuilder>(
                  content_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:MeshMS)
    }
    
    static {
      defaultInstance = new MeshMS(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:MeshMS)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MeshMS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MeshMS_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MeshMS_ContentElem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MeshMS_ContentElem_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014MeshMS.proto\"\302\001\n\006MeshMS\022\016\n\006sender\030\001 \001(" +
      "\t\022\021\n\trecipient\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\017\n\007ty" +
      "peInt\030\004 \001(\005\022\021\n\ttimestamp\030\005 \001(\003\022$\n\007conten" +
      "t\030\006 \003(\0132\023.MeshMS.ContentElem\032=\n\013ContentE" +
      "lem\022\014\n\004type\030\001 \001(\t\022\017\n\007typeInt\030\002 \001(\005\022\017\n\007co" +
      "ntent\030\003 \001(\tB*\n\030org.servalproject.meshmsB" +
      "\016MeshMSProtobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MeshMS_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MeshMS_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MeshMS_descriptor,
              new java.lang.String[] { "Sender", "Recipient", "Type", "TypeInt", "Timestamp", "Content", },
              org.servalproject.meshms.MeshMSProtobuf.MeshMS.class,
              org.servalproject.meshms.MeshMSProtobuf.MeshMS.Builder.class);
          internal_static_MeshMS_ContentElem_descriptor =
            internal_static_MeshMS_descriptor.getNestedTypes().get(0);
          internal_static_MeshMS_ContentElem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MeshMS_ContentElem_descriptor,
              new java.lang.String[] { "Type", "TypeInt", "Content", },
              org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.class,
              org.servalproject.meshms.MeshMSProtobuf.MeshMS.ContentElem.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
