/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_servalproject_system_BatmanPeerCount */

#ifndef _Included_org_servalproject_system_BatmanPeerCount
#define _Included_org_servalproject_system_BatmanPeerCount
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_servalproject_system_BatmanPeerCount_BatmanPeerCount
 * Method:    BatmanPeerCount
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jlong JNICALL Java_org_servalproject_system_BatmanPeerCount_BatmanPeerCount
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
